services:

  Elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    restart: always
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
    volumes:
#      - certs:/usr/share/elasticsearch/config/certs
      - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      xpack.security.enabled: false
      discovery.type: single-node
    ports:
      - '9200:9200'
    networks:
      - elk_network

  Logstash:
    image: docker.elastic.co/logstash/logstash:8.11.1
    container_name: logstash
    restart: always
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - /var/log/syslog/:/usr/share/logstash/ingest_data/
      - ./logstash.conf:/usr/share/logstash/pipline/logstash.conf:ro
    command: logstash -f /usr/share/logstash/pipline/logstash.conf
    ports:
      - '9600:9600'
    depends_on:
      Elasticsearch:
        condition: service_healthy
    networks:
      - elk_network

  Kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - '5601:5601'
    depends_on:
      Elasticsearch:
        condition: service_healthy
    networks:
      - elk_network


volumes:
  elastic_data:
  certs:

networks:
  elk_network:
    driver: bridge