services:

  Elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elasticsearch
    restart: always
    volumes:
#      - certs:/usr/share/elasticsearch/config/certs
      - elastic_data:/usr/share/elasticsearch/
    environment:
      xpack.security.enabled: false
      discovery.type: single-node
    ports:
      - '9200:9200'
    networks:
      - elk_network

  Logstash:
    image: docker.elastic.co/logstash/logstash:7.5.2
    container_name: logstash
    restart: always
    volumes:
      - /var/log/syslog:/usr/share/logstash/ingest_data
      - ./logstash.conf:/usr/share/logstash/pipline/logstash.conf:ro
    command: logstash -f /usr/share/logstash/pipline/logstash.conf
    ports:
      - '9600:9600'
    depends_on:
      - Elasticsearch
    networks:
      - elk_network

  Kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - '5601:5601'
    depends_on:
      - Elasticsearch
    networks:
      - elk_network


volumes:
  elastic_data:
  certs:

networks:
  elk_network:
    driver: bridge